### ISSUE TITLE
Not an issue, just a suggestion

### ISSUE THREAD

**Issue by yacineaa1** [juangburgos/QUaModbusClient#2]
Since Modbus is currently being phased out, why not use for example Snap7 to connect to Siemens clients (http://snap7.sourceforge.net/)

**Comment by juangburgos** [comment]
Thanks for your interest!

I like Snap7, but it is limited to Siemens. I needed a tool that would allow me to connect to virtually any PLC out there, and Modbus is still omnipresent (at least until OPC UA catches up). Actually there would be many other protocols I would consider more useful to connect to a wide arrange of PLCs, like IEC 60870-5-104, DNP3, IEC 61850, etc.

If there is commercial interest in a Snap7 based app, I would consider making an specific version.
